// Featured projects — bilingual titles, categories and descriptions
const projects=[
["Entertainment Events 1","humanitarian","Humanitarian · Entertainment","A dynamic entertainment video capturing children’s activities and authentic moments through energetic social-first editing.","videos/Humanitarian/Entertainment Events1.mp4","فعالية دمى","إنساني · ترفيه وفعاليات","فيديو ترفيهي ديناميكي يوثّق أنشطة الأطفال ولحظاتهم العفوية بأسلوب سريع وحيوي مناسب لمحتوى السوشيال ميديا."],
["Entertainment Events","humanitarian","Humanitarian · Entertainment","A warm and engaging children’s event video combining authentic reactions, playful activities and dynamic editing.","videos/Humanitarian/EntertainmentEvents.mp4","فعالية رسم","إنساني · ترفيه وفعاليات","فيديو دافئ وتفاعلي من فعالية للأطفال، يجمع بين ردود الفعل العفوية والأنشطة الإبداعية والمونتاج الديناميكي."],
["Entertainment Events 2","humanitarian","Humanitarian · Entertainment","An engaging community entertainment piece designed to capture joyful moments and create highly shareable social media content.","videos/Humanitarian/EntertainmentEvents2.mp4","فعالية ترفيه","إنساني · ترفيه وفعاليات","فيديو ترفيهي يوثّق فعالية مجتمعية ولحظات الفرح والتفاعل، مصمم ليكون جذابًا وقابلًا للمشاركة على السوشيال ميديا."],
["Human Story","humanitarian","Humanitarian · Human Story","A real human story transformed into an emotional visual narrative, focusing on authentic moments and meaningful details.","videos/Humanitarian/HumanStories.mp4","قصة انسانية","إنساني · قصة إنسانية","قصة إنسانية حقيقية تحوّلت إلى سرد بصري مؤثر يركّز على اللحظات الصادقة والتفاصيل التي تصنع ارتباطًا عاطفيًا مع الجمهور."],
["Humanitarian Appeal","humanitarian","Humanitarian · Appeal","An emotionally driven humanitarian appeal focused on a real case, crafted to communicate urgency, build empathy and motivate audience support.","videos/Humanitarian/HumanitarianAppeals.mp4","قصة إنسانية — مناشدة للدعم","إنساني · مناشدة إنسانية","مناشدة إنسانية مؤثرة تركز على حالة حقيقية، صُممت لإيصال الحاجة بوضوح وبناء التعاطف وتحفيز الجمهور على الدعم."],
["AI Automotive Film","ai","AI Video","AI-generated automotive commercial combining cinematic product visuals, camera movement and premium visual storytelling.","videos/ai-video/ai-01-automotive-film.mp4","فيلم سيارات بالذكاء الاصطناعي","فيديو بالذكاء الاصطناعي","إعلان سينمائي لسيارة من إنتاج الذكاء الاصطناعي، يجمع بين لقطات المنتج الفاخرة وحركة الكاميرا والسرد البصري الاحترافي."],
["Pistachio Cheesecake Commercial","ai","AI Video","AI-generated food commercial focused on cinematic product presentation, texture, lighting and appetizing close-up visuals.","videos/ai-video/ai-02-pistachio-cheesecake-commercial.mp4","إعلان تشيزكيك بالفستق","فيديو بالذكاء الاصطناعي","إعلان طعام بالذكاء الاصطناعي يركّز على تقديم المنتج بشكل سينمائي، مع إبراز الملمس والإضاءة واللقطات القريبة الشهية."],
["ZAYN Product Film","ai","AI Video","AI-assisted beauty product commercial built around cinematic macro shots, premium lighting and detailed product presentation.","videos/ai-video/ai-03-zayn-cosmetic-product-film.mp4","فيلم منتج ZAYN","فيديو بالذكاء الاصطناعي","إعلان لمنتج تجميلي مدعوم بالذكاء الاصطناعي، يعتمد على لقطات ماكرو سينمائية وإضاءة فاخرة وتفاصيل دقيقة للمنتج."],
["AI Food Storytelling","ai","AI Video","AI-generated short-form food story combining realistic characters, expressive close-ups and cinematic visual direction.","videos/ai-video/ai-04-food-storytelling.mp4","سرد قصصي للطعام بالذكاء الاصطناعي","فيديو بالذكاء الاصطناعي","قصة قصيرة عن الطعام من إنتاج الذكاء الاصطناعي، تجمع بين الشخصيات الواقعية واللقطات التعبيرية والتوجيه البصري السينمائي."],
["AI Character Commercial","ai","AI Video","AI-assisted character-driven product commercial combining realistic character shots, cinematic food and beverage close-ups, and polished product storytelling.","videos/ai-video/ai-05-character-commercial.mp4","إعلان شخصية بالذكاء الاصطناعي","فيديو بالذكاء الاصطناعي","إعلان منتج قائم على شخصية، مدعوم بالذكاء الاصطناعي، يجمع بين لقطات الشخصيات الواقعية واللقطات السينمائية للطعام والمشروبات."],
["Animated Infographic","motion","Motion Graphics","Vertical motion graphics piece combining illustrated characters, animated statistics and visual transitions to communicate a professional development message.","videos/motion-graphics/motion-02-animated-infographic.mp4","إنفوجرافيك متحرك","موشن جرافيك","قطعة موشن جرافيك عمودية تجمع بين الشخصيات المرسومة والإحصاءات المتحركة والانتقالات البصرية لإيصال رسالة تطويرية بشكل واضح."],
["An'am App Promo","motion","Motion Graphics","Promotional motion graphic for the An'am app, combining UI animation, phone mockups, map visuals and clear calls to action.","videos/motion-graphics/motion-04-app-promo.mp4","إعلان تطبيق أنعام","موشن جرافيك","فيديو ترويجي لتطبيق أنعام يجمع بين تحريك واجهة المستخدم ونماذج الهواتف والخرائط والدعوات الواضحة لاتخاذ إجراء."],
["VDIT Corporate Promo","motion","Motion Graphics","Corporate promotional video for VDIT, combining branded visuals, animated information, character-based storytelling and a clear contact-focused closing sequence.","videos/motion-graphics/motion-05-vdit-corporate-promo.mp4","إعلان VDIT للشركات","موشن جرافيك","فيديو ترويجي مؤسسي لـ VDIT يجمع بين الهوية البصرية والمعلومات المتحركة والسرد القائم على الشخصيات ونهاية واضحة للتواصل."],
["Explainer Motion Design","motion","Motion Graphics","Short-form animated explainer built around illustrated scenes, icons, kinetic elements and smooth transitions.","videos/motion-graphics/motion-03-explainer.mp4","فيديو موشن توضيحي","موشن جرافيك","فيديو موشن توضيحي قصير يعتمد على مشاهد مرسومة وأيقونات وعناصر حركية وانتقالات سلسة لشرح الفكرة بطريقة جذابة."],
["Healthcare Awareness Explainer","motion","Motion Graphics","Animated healthcare awareness video with branded illustrations, typography and clean information design.","videos/motion-graphics/motion-01-health-corporate.mp4","فيديو توعوي صحي","موشن جرافيك","فيديو توعوي صحي متحرك يستخدم الرسومات المرتبطة بالهوية والطباعة المتحركة وتصميم المعلومات بشكل واضح ومنظم."]
];
